/**
 * My NPM Module
 * A simple Node.js module with database utilities
 */

const { sendNotFound, sendConflict, sendInternalServerError, sendServiceUnavailable, validateResponseObject, sanitizeMessage, getTimestamp, sendValidationError, sendAuthError, generateRequestId } = require('./lib/http-utils');
const { ensureMongoDB, ensureUnique, handleMongoError, safeDbOperation, retryDbOperation, ensureIdempotency, optimizeQuery, createAggregationPipeline } = require('./lib/database-utils');
const { findDocumentById, updateDocumentById, deleteDocumentById, cascadeDeleteDocument, createDocument, findDocuments, findOneDocument, bulkUpdateDocuments } = require('./lib/document-helpers');
const { performUserDocOp, findUserDoc, deleteUserDoc, userDocActionOr404, fetchUserDocOr404, deleteUserDocOr404, listUserDocs, createUniqueDoc, updateUserDoc, validateDocumentUniqueness, hasUniqueFieldChanges } = require('./lib/document-ops');
const { MemStorage, storage } = require('./lib/storage');
const { greet, add, isEven, dedupeByFirst, dedupeByLowercaseFirst, dedupeByLast, dedupe } = require('./lib/utils');
const { getEmails, createEmailTarget, isValidEmail, normalizeEmail, getEmailDomain, filterValidEmails } = require('./lib/email-utils');
const { CircuitBreaker, createCircuitBreaker, STATES: CIRCUIT_BREAKER_STATES } = require('./lib/circuit-breaker');
const { CircuitBreakerFactory, getCircuitBreakerFactory, getManagedCircuitBreaker, getCircuitBreakerStats, getCircuitBreakerFactoryStats, clearAllCircuitBreakers, shutdownCircuitBreakerFactory } = require('./lib/circuit-breaker-factory');
const { updateMetrics: updateHealthMetrics, incrementActiveRequests, decrementActiveRequests, getRequestMetrics, resetMetrics: resetHealthMetrics, checkMemoryHealth, checkCpuHealth, checkFilesystemHealth, runCustomCheck, determineOverallStatus, getHealthStatus, healthCheckMiddleware, readinessCheckMiddleware, livenessCheckMiddleware, setupHealthRoutes } = require('./lib/health-check');
const { TestMemoryManager, createMemoryManager, createLeakDetectionSession, quickMemoryCheck, withMemoryTracking, setupTestMemoryMonitoring, teardownTestMemoryMonitoring } = require('./lib/test-memory-manager');
const { AsyncQueue, createQueue } = require('./lib/async-queue');
const { SimpleDatabasePool, DatabaseConnectionPool, databaseConnectionPool, createDatabasePool, acquireDatabaseConnection, releaseDatabaseConnection, executeDatabaseQuery, getDatabasePoolStats, getDatabasePoolHealth, shutdownDatabasePools } = require('./lib/database-pool');
const { createCrudService, createPaginatedService, createValidatedService, findByFieldIgnoreCase, createDuplicateError, escapeRegex: escapeRegexCrud, validateData } = require('./lib/crud-service-factory');
const { checkDuplicateByField, validateUniqueField, validateUniqueFields, createUniqueValidator, handleDuplicateKeyError, withDuplicateKeyHandling, createUniqueFieldMiddleware, createUniqueFieldsMiddleware, isDuplicateError, createBatchUniqueChecker } = require('./lib/unique-validator');
const { safeJsonStringify, safeJsonParse, JSON } = require('./lib/streaming-json');
const { FastMath, FastString, LockFreeQueue, ObjectPool, FastTimer, FastMemory, FastHash, FastOps, Cast, Prop } = require('./lib/fast-operations');
const { logFunctionEntry, logFunctionExit, logFunctionError } = require('./lib/logging-utils');
const { validatePagination, createPaginationMeta, createPaginatedResponse, validateCursorPagination, createCursor, createCursorPaginationMeta, createCursorPaginatedResponse, validateSorting } = require('./lib/pagination-utils');
const { DatabaseMetrics, RequestMetrics, SystemMetrics, PerformanceMonitor, performanceMonitor } = require('./lib/performance-utils');
const { createRedisClient, redis } = require('./lib/cache-utils');
const { LRUCache } = require('./lib/lru-cache');
const { incCacheHit, incCacheMiss, setCacheKeys, getCacheMetrics, resetCacheMetrics } = require('./lib/perf');
const { normalizeFieldName, getCollectionName, denormalizeFieldName, normalizeObjectFields, denormalizeObjectFields } = require('./lib/field-utils');
const { getMongoType, getSupportedTypes, isSupportedType } = require('./lib/typeMap');
const { mapParameterToMongoType, mapParametersToSchema, generateMongooseSchema, generateMongoSchema } = require('./lib/mongoose-mapper');
const { IStorage, MemoryBinaryStorage, FileSystemBinaryStorage, StorageFactory, getDefaultStorage } = require('./lib/binary-storage');
const { serializeDocument, serializeMongooseDocument, mapAndSerialize, saveAndSerialize, mapAndSerializeObj, serializeDocumentObj, serializeMongooseDocumentObj, saveAndSerializeObj, safeSerializeDocument, safeMapAndSerialize, serializeFields, serializeWithoutFields } = require('./lib/serialization-utils');

module.exports = {
  sendNotFound,
  sendConflict,
  sendInternalServerError,
  sendServiceUnavailable,
  validateResponseObject,
  sanitizeMessage,
  getTimestamp,
  generateRequestId,
  ensureMongoDB,
  ensureUnique,
  handleMongoError,
  safeDbOperation,
  retryDbOperation,
  ensureIdempotency,
  optimizeQuery,
  createAggregationPipeline,
  findDocumentById,
  updateDocumentById,
  deleteDocumentById,
  cascadeDeleteDocument,
  createDocument,
  findDocuments,
  findOneDocument,
  bulkUpdateDocuments,
  performUserDocOp,
  findUserDoc,
  deleteUserDoc,
  userDocActionOr404,
  fetchUserDocOr404,
  deleteUserDocOr404,
  listUserDocs,
  createUniqueDoc,
  updateUserDoc,
  validateDocumentUniqueness,
  hasUniqueFieldChanges,
  MemStorage,
  storage,
  greet,
  add,
  isEven,
  dedupeByFirst,
  dedupeByLowercaseFirst,
  dedupeByLast,
  dedupe,
  getEmails,
  createEmailTarget,
  isValidEmail,
  normalizeEmail,
  getEmailDomain,
  filterValidEmails,
  CircuitBreaker,
  createCircuitBreaker,
  CIRCUIT_BREAKER_STATES,
  CircuitBreakerFactory,
  getCircuitBreakerFactory,
  getManagedCircuitBreaker,
  getCircuitBreakerStats,
  getCircuitBreakerFactoryStats,
  clearAllCircuitBreakers,
  shutdownCircuitBreakerFactory,
  updateHealthMetrics,
  incrementActiveRequests,
  decrementActiveRequests,
  getRequestMetrics,
  resetHealthMetrics,
  checkMemoryHealth,
  checkCpuHealth,
  checkFilesystemHealth,
  runCustomCheck,
  determineOverallStatus,
  getHealthStatus,
  healthCheckMiddleware,
  readinessCheckMiddleware,
  livenessCheckMiddleware,
  setupHealthRoutes,
  TestMemoryManager,
  createMemoryManager,
  createLeakDetectionSession,
  quickMemoryCheck,
  withMemoryTracking,
  setupTestMemoryMonitoring,
  teardownTestMemoryMonitoring,
  AsyncQueue,
  createQueue,
  SimpleDatabasePool,
  DatabaseConnectionPool,
  databaseConnectionPool,
  createDatabasePool,
  acquireDatabaseConnection,
  releaseDatabaseConnection,
  executeDatabaseQuery,
  getDatabasePoolStats,
  getDatabasePoolHealth,
  shutdownDatabasePools,
  createCrudService,
  createPaginatedService,
  createValidatedService,
  findByFieldIgnoreCase,
  createDuplicateError,
  escapeRegexCrud,
  validateData,
  checkDuplicateByField,
  validateUniqueField,
  validateUniqueFields,
  createUniqueValidator,
  handleDuplicateKeyError,
  withDuplicateKeyHandling,
  createUniqueFieldMiddleware,
  createUniqueFieldsMiddleware,
  isDuplicateError,
  createBatchUniqueChecker,
  safeJsonStringify,
  safeJsonParse,
  JSON,
  FastMath,
  FastString,
  LockFreeQueue,
  ObjectPool,
  FastTimer,
  FastMemory,
  FastHash,
  FastOps,
  Cast,
  Prop,
  logFunctionEntry,
  logFunctionExit,
  logFunctionError,
  validatePagination,
  createPaginationMeta,
  createPaginatedResponse,
  validateCursorPagination,
  createCursor,
  createCursorPaginationMeta,
  createCursorPaginatedResponse,
  validateSorting,
  DatabaseMetrics,
  RequestMetrics,
  SystemMetrics,
  PerformanceMonitor,
  performanceMonitor,
  createRedisClient,
  redis,
  LRUCache,
  incCacheHit,
  incCacheMiss,
  setCacheKeys,
  getCacheMetrics,
  resetCacheMetrics,
  normalizeFieldName,
  getCollectionName,
  denormalizeFieldName,
  normalizeObjectFields,
  denormalizeObjectFields,
  getMongoType,
  getSupportedTypes,
  isSupportedType,
  mapParameterToMongoType,
  mapParametersToSchema,
  generateMongooseSchema,
  generateMongoSchema,
  IStorage,
  MemoryBinaryStorage,
  FileSystemBinaryStorage,
  StorageFactory,
  getDefaultStorage,
  serializeDocument,
  serializeMongooseDocument,
  mapAndSerialize,
  saveAndSerialize,
  mapAndSerializeObj,
  serializeDocumentObj,
  serializeMongooseDocumentObj,
  saveAndSerializeObj,
  safeSerializeDocument,
  safeMapAndSerialize,
  serializeFields,
  serializeWithoutFields
};